name: Feature Request
description: Suggest a new feature
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: feature
    attributes:
      label: Feature description
      description: Describe the feature you want.
    validations:
      required: true

  - type: textarea
    id: why
    attributes:
      label: Why is this useful?
      description: Explain why this feature should be added.
